/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:fc831268-f090-4a65-af35-551109bc4952",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_tvHQuQAzf",
    "aws_user_pools_web_client_id": "6lsa53ojh8qjuffekkbs81g0d6",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplifyapp-storage232615-staging",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://idzm5dsrsfhqdhzcutuck2ipam.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oujl3kypg5ajpd6b3fytjsfcla"
};


export default awsmobile;
