/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:6515f2d5-73fb-4555-bd46-9fecbf5b8954",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_bmgONBPVI",
    "aws_user_pools_web_client_id": "igqqq0e2drjmplo0nfp1l8rqu",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://idzm5dsrsfhqdhzcutuck2ipam.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oujl3kypg5ajpd6b3fytjsfcla"
};


export default awsmobile;
